<?php
/**
 * ACF Flexible Constructor: s_flexibol_constructor
 */

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
	return;
}

add_action( 'acf/init', 's_flexibol_register_constructor_fields' );

function s_flexibol_register_constructor_fields() {

	acf_add_local_field_group( array(
		'key'    => 'group_s_flexibol_constructor',
		'title'  => 'Flexible Constructor (s_flexibol)',
		'fields' => array(
			array(
				'key'          => 'field_s_flexibol_constructor',
				'label'        => 'Конструктор блоков',
				'name'         => 's_flexibol_constructor',
				'type'         => 'flexible_content',
				'button_label' => 'Add block',
				'layouts'      => array(

					// Макет 1: текст о стране
					'layout_s_flexibol_country_text' => array(
						'key'        => 'layout_s_flexibol_country_text',
						'name'       => 's_flexibol_country_text',
						'label'      => 'Текст о стране',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_country_text_s_flexibol_title',
								'label' => 'Title',
								'name'  => 's_flexibol_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_country_text_s_flexibol_text',
								'label' => 'Text',
								'name'  => 's_flexibol_text',
								'type'  => 'wysiwyg',
								'tabs'  => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_country_text_s_flexibol_image',
								'label'         => 'Image',
								'name'          => 's_flexibol_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'   => 'field_s_flexibol_country_text_s_flexibol_text_2',
								'label' => 'Text (2)',
								'name'  => 's_flexibol_text_2',
								'type'  => 'wysiwyg',
								'tabs'  => 'all',
							),
				
						),
					),

				  // 		 Макет 2.0: карта			
					'layout_s_flexibol_map' => array(
						'key'     => 'layout_s_flexibol_map',
						'name'    => 's_flexibol_map',
						'label'   => 'Карта',
						'display' => 'block',
						'sub_fields' => array(), // ПУСТО
					),
					// Макет 2.005: reviews block from template-parts/reviews
					'layout_s_flexibol_custom_reviews' => array(
						'key'     => 'layout_s_flexibol_custom_reviews',
						'name'    => 's_flexibol_custom_reviews',
						'label'   => 'общие отзывы',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'           => 'field_s_flexibol_custom_reviews_toggle',
								'label'         => 'Show reviews block',
								'name'          => 'custom_reviews',
								'type'          => 'true_false',
								'ui'            => 1,
								'default_value' => 1,
							),
						),
					),
					// Макет 2.006: template-parts/slider_our_experience.php
					'layout_s_flexibol_custom_regions' => array(
						'key'     => 'layout_s_flexibol_custom_regions',
						'name'    => 's_flexibol_custom_regions',
						'label'   => 'регионы слайдер',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'           => 'field_s_flexibol_custom_regions_toggle',
								'label'         => 'Показывать блок',
								'name'          => 'custom_regions',
								'type'          => 'true_false',
								'ui'            => 1,
								'default_value' => 1,
							),
						),
					),
					// Макет 2.007: template-parts/slider_city.php
					'layout_s_flexibol_custom_city_slider' => array(
						'key'     => 'layout_s_flexibol_custom_city_slider',
						'name'    => 's_flexibol_custom_city_slider',
						'label'   => 'города слайдер',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'           => 'field_s_flexibol_custom_city_slider_toggle',
								'label'         => 'Показывать блок',
								'name'          => 'custom_city_slider',
								'type'          => 'true_false',
								'ui'            => 1,
								'default_value' => 1,
							),
						),
					),
					// Макет 2.01: видео‑отзывы
					'layout_s_flexibol_video_reviews' => array(
						'key'        => 'layout_s_flexibol_video_reviews',
						'name'       => 's_flexibol_video_reviews',
						'label'      => 'Видео-отзывы',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_video_reviews_s_flexibol_section_title',
								'label' => 'Section title',
								'name'  => 's_flexibol_section_title',
								'type'  => 'text',
							),
							// Video 1
							array(
								'key'   => 'field_s_flexibol_video_response_video_1_title',
								'label' => 'Video 1 title',
								'name'  => 's_flexibol_video_1_title',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_video_response_video_1_image',
								'label'         => 'Video 1 image',
								'name'          => 's_flexibol_video_1_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_video_response_video_1_embed',
								'label'         => 'Video 1 — regular link',
								'name'          => 's_flexibol_video_1_embed',
								'type'          => 'textarea',
								'rows'          => 4,
								'instructions'  => 'YouTube/Vimeo URL or iframe embed (horizontal video).',
							),
							array(
								'key'          => 'field_s_flexibol_video_response_video_1_short',
								'label'        => 'Video 1 — Shorts link',
								'name'         => 's_flexibol_video_1_short',
								'type'         => 'textarea',
								'rows'         => 3,
								'instructions' => 'YouTube Shorts URL (e.g. youtube.com/shorts/…). Opens vertical player if filled.',
							),
							// Video 2
							array(
								'key'   => 'field_s_flexibol_video_response_video_2_title',
								'label' => 'Video 2 title',
								'name'  => 's_flexibol_video_2_title',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_video_response_video_2_image',
								'label'         => 'Video 2 image',
								'name'          => 's_flexibol_video_2_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_video_response_video_2_embed',
								'label'         => 'Video 2 — regular link',
								'name'          => 's_flexibol_video_2_embed',
								'type'          => 'textarea',
								'rows'          => 4,
								'instructions'  => 'YouTube/Vimeo URL or iframe embed (horizontal video).',
							),
							array(
								'key'          => 'field_s_flexibol_video_response_video_2_short',
								'label'        => 'Video 2 — Shorts link',
								'name'         => 's_flexibol_video_2_short',
								'type'         => 'textarea',
								'rows'         => 3,
								'instructions' => 'YouTube Shorts URL. Opens vertical player if filled.',
							),
							// Video 3
							array(
								'key'   => 'field_s_flexibol_video_response_video_3_title',
								'label' => 'Video 3 title',
								'name'  => 's_flexibol_video_3_title',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_video_response_video_3_image',
								'label'         => 'Video 3 image',
								'name'          => 's_flexibol_video_3_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_video_response_video_3_embed',
								'label'         => 'Video 3 — regular link',
								'name'          => 's_flexibol_video_3_embed',
								'type'          => 'textarea',
								'rows'          => 4,
								'instructions'  => 'YouTube/Vimeo URL or iframe embed (horizontal video).',
							),
							array(
								'key'          => 'field_s_flexibol_video_response_video_3_short',
								'label'        => 'Video 3 — Shorts link',
								'name'         => 's_flexibol_video_3_short',
								'type'         => 'textarea',
								'rows'         => 3,
								'instructions' => 'YouTube Shorts URL. Opens vertical player if filled.',
							),
							// Extra text under videos
							array(
								'key'          => 'field_s_flexibol_video_response_extra_text',
								'label'        => 'Extra text (under videos)',
								'name'         => 's_flexibol_extra_text',
								'type'         => 'text',
								'instructions' => 'Short text shown under the videos.',
							),
						),
					),

					// Отзывы туристов (flex): фото, имя, текст — без звёзд (аналог слайдера из tourist_reviews).
					'layout_s_flexibol_tourist_reviews' => array(
						'key'        => 'layout_s_flexibol_tourist_reviews',
						'name'       => 's_flexibol_tourist_reviews',
						'label'      => 'Отзывы туристов (flex)',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_tourist_block_title',
								'label' => 'Заголовок блока',
								'name'  => 's_flexibol_tourist_block_title',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_tourist_reviews_background_image',
								'label'         => 'Фотка бекграунда',
								'name'          => 's_flexibol_tourist_reviews_background_image',
								'type'          => 'image',
								'instructions'  => 'Фон для секции s-flexibol-tourist-reviews. Если пусто — фон не выводится.',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'            => 'field_s_flexibol_tourist_items',
								'label'          => 'Отзывы',
								'name'           => 's_flexibol_tourist_items',
								'type'           => 'repeater',
								'button_label'   => 'Добавить отзыв',
								'layout'         => 'block',
								'pagination'     => 0,
								'min'            => 0,
								'max'            => 0,
								'collapsed'      => 'field_s_flexibol_tourist_item_name',
								'sub_fields'     => array(
									array(
										'key'           => 'field_s_flexibol_tourist_item_photo',
										'label'         => 'Фото',
										'name'          => 's_flexibol_tourist_photo',
										'type'          => 'image',
										'return_format' => 'array',
										'preview_size'  => 'medium',
										'library'       => 'all',
									),
									array(
										'key'   => 'field_s_flexibol_tourist_item_name',
										'label' => 'Имя',
										'name'  => 's_flexibol_tourist_name',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_tourist_item_text',
										'label' => 'Текст отзыва',
										'name'  => 's_flexibol_tourist_text',
										'type'  => 'textarea',
										'rows'  => 5,
									),
								),
							),
						),
					),

					// Layout 3: Seasons line (12 fixed months)
					'layout_s_flexibol_seasons_line' => array(
						'key'        => 'layout_s_flexibol_seasons_line',
						'name'       => 's_flexibol_seasons_line',
						'label'      => 'Линия сезонов',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_seasons_line_section_title',
								'label' => 'Заголовок линии сезонов',
								'name'  => 's_flexibol_seasons_line_section_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_pod_zag_pogoda',
								'label' => 'Подзаголовок',
								'name'  => 'pod_zag_pogoda',
								'type'  => 'textarea',
								'rows'  => 3,
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_background_image',
								'label'         => 'Фотка бекграунда',
								'name'          => 's_flexibol_seasons_line_background_image',
								'type'          => 'image',
								'instructions'  => 'Фон для секции slider-pogoda.',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_shadow_image',
								'label'         => 'Фотка тени (Ellipse523)',
								'name'          => 's_flexibol_seasons_line_shadow_image',
								'type'          => 'image',
								'instructions'  => 'Картинка для img.Ellipse523.',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							// JANUARY
							array(
								'key'   => 'field_s_flexibol_seasons_line_january_title',
								'label' => 'January title',
								'name'  => 's_flexibol_season_january_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_january_subtitle',
								'label' => 'January subtitle',
								'name'  => 's_flexibol_season_january_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_january_short_text',
								'label' => 'January short text',
								'name'  => 's_flexibol_season_january_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_january_main_image',
								'label'         => 'January main image',
								'name'          => 's_flexibol_season_january_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_january_weather_icon',
								'label'         => 'January weather icon',
								'name'          => 's_flexibol_season_january_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// FEBRUARY
							array(
								'key'   => 'field_s_flexibol_seasons_line_february_title',
								'label' => 'February title',
								'name'  => 's_flexibol_season_february_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_february_subtitle',
								'label' => 'February subtitle',
								'name'  => 's_flexibol_season_february_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_february_short_text',
								'label' => 'February short text',
								'name'  => 's_flexibol_season_february_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_february_main_image',
								'label'         => 'February main image',
								'name'          => 's_flexibol_season_february_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_february_weather_icon',
								'label'         => 'February weather icon',
								'name'          => 's_flexibol_season_february_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// MARCH
							array(
								'key'   => 'field_s_flexibol_seasons_line_march_title',
								'label' => 'March title',
								'name'  => 's_flexibol_season_march_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_march_subtitle',
								'label' => 'March subtitle',
								'name'  => 's_flexibol_season_march_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_march_short_text',
								'label' => 'March short text',
								'name'  => 's_flexibol_season_march_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_march_main_image',
								'label'         => 'March main image',
								'name'          => 's_flexibol_season_march_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_march_weather_icon',
								'label'         => 'March weather icon',
								'name'          => 's_flexibol_season_march_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// APRIL
							array(
								'key'   => 'field_s_flexibol_seasons_line_april_title',
								'label' => 'April title',
								'name'  => 's_flexibol_season_april_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_april_subtitle',
								'label' => 'April subtitle',
								'name'  => 's_flexibol_season_april_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_april_short_text',
								'label' => 'April short text',
								'name'  => 's_flexibol_season_april_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_april_main_image',
								'label'         => 'April main image',
								'name'          => 's_flexibol_season_april_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_april_weather_icon',
								'label'         => 'April weather icon',
								'name'          => 's_flexibol_season_april_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// MAY
							array(
								'key'   => 'field_s_flexibol_seasons_line_may_title',
								'label' => 'May title',
								'name'  => 's_flexibol_season_may_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_may_subtitle',
								'label' => 'May subtitle',
								'name'  => 's_flexibol_season_may_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_may_short_text',
								'label' => 'May short text',
								'name'  => 's_flexibol_season_may_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_may_main_image',
								'label'         => 'May main image',
								'name'          => 's_flexibol_season_may_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_may_weather_icon',
								'label'         => 'May weather icon',
								'name'          => 's_flexibol_season_may_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// JUNE
							array(
								'key'   => 'field_s_flexibol_seasons_line_june_title',
								'label' => 'June title',
								'name'  => 's_flexibol_season_june_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_june_subtitle',
								'label' => 'June subtitle',
								'name'  => 's_flexibol_season_june_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_june_short_text',
								'label' => 'June short text',
								'name'  => 's_flexibol_season_june_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_june_main_image',
								'label'         => 'June main image',
								'name'          => 's_flexibol_season_june_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_june_weather_icon',
								'label'         => 'June weather icon',
								'name'          => 's_flexibol_season_june_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// JULY
							array(
								'key'   => 'field_s_flexibol_seasons_line_july_title',
								'label' => 'July title',
								'name'  => 's_flexibol_season_july_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_july_subtitle',
								'label' => 'July subtitle',
								'name'  => 's_flexibol_season_july_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_july_short_text',
								'label' => 'July short text',
								'name'  => 's_flexibol_season_july_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_july_main_image',
								'label'         => 'July main image',
								'name'          => 's_flexibol_season_july_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_july_weather_icon',
								'label'         => 'July weather icon',
								'name'          => 's_flexibol_season_july_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// AUGUST
							array(
								'key'   => 'field_s_flexibol_seasons_line_august_title',
								'label' => 'August title',
								'name'  => 's_flexibol_season_august_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_august_subtitle',
								'label' => 'August subtitle',
								'name'  => 's_flexibol_season_august_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_august_short_text',
								'label' => 'August short text',
								'name'  => 's_flexibol_season_august_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_august_main_image',
								'label'         => 'August main image',
								'name'          => 's_flexibol_season_august_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_august_weather_icon',
								'label'         => 'August weather icon',
								'name'          => 's_flexibol_season_august_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// SEPTEMBER
							array(
								'key'   => 'field_s_flexibol_seasons_line_september_title',
								'label' => 'September title',
								'name'  => 's_flexibol_season_september_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_september_subtitle',
								'label' => 'September subtitle',
								'name'  => 's_flexibol_season_september_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_september_short_text',
								'label' => 'September short text',
								'name'  => 's_flexibol_season_september_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_september_main_image',
								'label'         => 'September main image',
								'name'          => 's_flexibol_season_september_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_september_weather_icon',
								'label'         => 'September weather icon',
								'name'          => 's_flexibol_season_september_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// OCTOBER
							array(
								'key'   => 'field_s_flexibol_seasons_line_october_title',
								'label' => 'October title',
								'name'  => 's_flexibol_season_october_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_october_subtitle',
								'label' => 'October subtitle',
								'name'  => 's_flexibol_season_october_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_october_short_text',
								'label' => 'October short text',
								'name'  => 's_flexibol_season_october_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_october_main_image',
								'label'         => 'October main image',
								'name'          => 's_flexibol_season_october_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_october_weather_icon',
								'label'         => 'October weather icon',
								'name'          => 's_flexibol_season_october_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// NOVEMBER
							array(
								'key'   => 'field_s_flexibol_seasons_line_november_title',
								'label' => 'November title',
								'name'  => 's_flexibol_season_november_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_november_subtitle',
								'label' => 'November subtitle',
								'name'  => 's_flexibol_season_november_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_november_short_text',
								'label' => 'November short text',
								'name'  => 's_flexibol_season_november_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_november_main_image',
								'label'         => 'November main image',
								'name'          => 's_flexibol_season_november_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_november_weather_icon',
								'label'         => 'November weather icon',
								'name'          => 's_flexibol_season_november_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
							// DECEMBER
							array(
								'key'   => 'field_s_flexibol_seasons_line_december_title',
								'label' => 'December title',
								'name'  => 's_flexibol_season_december_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_december_subtitle',
								'label' => 'December subtitle',
								'name'  => 's_flexibol_season_december_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_seasons_line_december_short_text',
								'label' => 'December short text',
								'name'  => 's_flexibol_season_december_short_text',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_december_main_image',
								'label'         => 'December main image',
								'name'          => 's_flexibol_season_december_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_seasons_line_december_weather_icon',
								'label'         => 'December weather icon',
								'name'          => 's_flexibol_season_december_weather_icon',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'thumbnail',
								'library'       => 'all',
							),
						),
					),

					// Layout 4: Regions comparison
					'layout_s_flexibol_regions_comparison' => array(
						'key'     => 'layout_s_flexibol_regions_comparison',
						'name'    => 's_flexibol_regions_comparison',
						'label'   => 'Сравнение регионов',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_regions_comparison_section_title',
								'label' => 'Section title',
								'name'  => 's_flexibol_regions_comparison_section_title',
								'type'  => 'text',
								'default_value' => 'Regions comparison',
							),
							array(
								'key'   => 'field_s_flexibol_regions_comparison_dop_text',
								'label' => 'Текст под заголовком',
								'name'  => 'comparison_of_regions_dop_text',
								'type'  => 'textarea',
								'rows'  => 3,
							),
							// Static left column
							array(
								'key'   => 'field_s_flexibol_regions_left_title',
								'label' => 'Left block title',
								'name'  => 's_flexibol_regions_left_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_regions_left_subtitle',
								'label' => 'Left block subtitle',
								'name'  => 's_flexibol_regions_left_subtitle',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_regions_label_weather',
								'label' => 'Row label: Weather',
								'name'  => 's_flexibol_regions_label_weather',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_regions_label_entertainment',
								'label' => 'Row label: Entertainment',
								'name'  => 's_flexibol_regions_label_entertainment',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_regions_label_transport',
								'label' => 'Row label: Transport',
								'name'  => 's_flexibol_regions_label_transport',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_regions_label_kids',
								'label' => 'Row label: Kids entertainment',
								'name'  => 's_flexibol_regions_label_kids',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_regions_label_price',
								'label' => 'Row label: Price',
								'name'  => 's_flexibol_regions_label_price',
								'type'  => 'text',
							),

							// Regions repeater (right columns)
							array(
								'key'          => 'field_s_flexibol_regions_items',
								'label'        => 'Regions (columns)',
								'name'         => 's_flexibol_regions_items',
								'type'         => 'repeater',
								'button_label' => 'Add region',
								'layout'       => 'row',
								'sub_fields'   => array(
									array(
										'key'   => 'field_s_flexibol_regions_item_city_name',
										'label' => 'City / region name',
										'name'  => 's_flexibol_region_city_name',
										'type'  => 'text',
									),
									array(
										'key'           => 'field_s_flexibol_regions_item_image',
										'label'         => 'City image',
										'name'          => 's_flexibol_region_image',
										'type'          => 'image',
										'return_format' => 'array',
										'preview_size'  => 'medium',
										'library'       => 'all',
									),
									array(
										'key'   => 'field_s_flexibol_regions_item_weather',
										'label' => 'Weather value',
										'name'  => 's_flexibol_region_weather',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_regions_item_entertainment',
										'label' => 'Entertainment value',
										'name'  => 's_flexibol_region_entertainment',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_regions_item_transport',
										'label' => 'Transport value',
										'name'  => 's_flexibol_region_transport',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_regions_item_kids',
										'label' => 'Kids entertainment value',
										'name'  => 's_flexibol_region_kids',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_regions_item_price',
										'label' => 'Price value',
										'name'  => 's_flexibol_region_price',
										'type'  => 'text',
									),
								),
							),
						),
					),

					// Layout 5: Questions & Answers (FAQ)
					'layout_s_flexibol_faq' => array(
						'key'     => 'layout_s_flexibol_faq',
						'name'    => 's_flexibol_faq',
						'label'   => 'Вопросы и ответы',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_faq_main_title',
								'label' => 'FAQ main title',
								'name'  => 's_flexibol_faq_main_title',
								'type'  => 'text',
							),
							array(
								'key'          => 'field_s_flexibol_faq_items',
								'label'        => 'Questions list',
								'name'         => 's_flexibol_faq_items',
								'type'         => 'repeater',
								'layout'       => 'row',
								'button_label' => 'Add question',
								'sub_fields'   => array(
									array(
										'key'   => 'field_s_flexibol_faq_item_question',
										'label' => 'Question',
										'name'  => 's_flexibol_faq_question',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_faq_item_answer',
										'label' => 'Answer',
										'name'  => 's_flexibol_faq_answer',
										'type'  => 'textarea',
										'rows'  => 4,
									),
								),
							),
						),
					),

					// Layout 7: Attractions slider
					'layout_s_flexibol_attractions_slider' => array(
						'key'     => 'layout_s_flexibol_attractions_slider',
						'name'    => 's_flexibol_attractions_slider',
						'label'   => 'Слайдер достопримечательностей',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_attractions_slider_title',
								'label' => 'Заголовок блока',
								'name'  => 's_flexibol_attractions_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_attractions_dop_text_landmark',
								'label' => 'Текст под заголовком',
								'name'  => 'dop_text_landmark',
								'type'  => 'textarea',
								'rows'  => 3,
							),
							array(
								'key'           => 'field_s_flexibol_attractions_background_image',
								'label'         => 'Фотка бекграунда',
								'name'          => 's_flexibol_attractions_background_image',
								'type'          => 'image',
								'instructions'  => 'Фон для секции landmark.',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_attractions_shadow_image',
								'label'         => 'Фотка тени',
								'name'          => 's_flexibol_attractions_shadow_image',
								'type'          => 'image',
								'instructions'  => 'Картинка вместо blue2.webp (class elips099).',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'          => 'field_s_flexibol_attractions_slider_items',
								'label'        => 'Slider cards',
								'name'         => 's_flexibol_attractions_items',
								'type'         => 'repeater',
								'layout'       => 'row',
								'button_label' => 'Add card',
								'sub_fields'   => array(
									array(
										'key'   => 'field_s_flexibol_attractions_card_title',
										'label' => 'Card title',
										'name'  => 's_flexibol_attractions_card_title',
										'type'  => 'text',
									),
									array(
										'key'           => 'field_s_flexibol_attractions_card_image',
										'label'         => 'Card image',
										'name'          => 's_flexibol_attractions_image',
										'type'          => 'image',
										'return_format' => 'array',
										'preview_size'  => 'medium',
										'library'       => 'all',
									),
									array(
										'key'   => 'field_s_flexibol_attractions_card_text',
										'label' => 'Card text',
										'name'  => 's_flexibol_attractions_text',
										'type'  => 'textarea',
										'rows'  => 4,
									),
									array(
										'key'   => 'field_s_flexibol_attractions_card_button_text',
										'label' => 'Button name',
										'name'  => 's_flexibol_attractions_button_text',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_attractions_card_button_link',
										'label' => 'Button link',
										'name'  => 's_flexibol_attractions_button_link',
										'type'  => 'text',
									),
								),
							),
						),
					),

					// Layout 8: Multi-day route (один заголовок на все дни + репитер дней)
					'layout_s_flexibol_route_one_day' => array(
						'key'     => 'layout_s_flexibol_route_one_day',
						'name'    => 's_flexibol_route_one_day',
						'label'   => 'Маршрут (несколько дней)',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_route_section_title',
								'label' => 'Общий заголовок маршрута',
								'name'  => 's_flexibol_route_section_title',
								'type'  => 'text',
								'instructions' => 'Один заголовок на весь блок (например: «Примерный маршрут на 3 дня»).',
							),
							array(
								'key'   => 'field_s_flexibol_route_dop_text',
								'label' => 'Текст под заголовком',
								'name'  => 'rout_dop_text',
								'type'  => 'textarea',
								'rows'  => 3,
							),
							array(
								'key'          => 'field_s_flexibol_route_days',
								'label'        => 'Дни маршрута',
								'name'         => 's_flexibol_route_days',
								'type'         => 'repeater',
								'layout'       => 'block',
								'button_label' => 'Добавить день',
								'sub_fields'   => array(
									array(
										'key'   => 'field_s_flexibol_route_day_badge',
										'label' => 'Бейдж дня',
										'name'  => 's_flexibol_route_day_badge',
										'type'  => 'text',
										'default_value' => 'День 1',
										'instructions' => 'Например: «день 1», «День 2».',
									),
									array(
										'key'   => 'field_s_flexibol_route_day_subtitle',
										'label' => 'Подзаголовок дня',
										'name'  => 's_flexibol_route_day_subtitle',
										'type'  => 'text',
										'instructions' => 'Строка рядом с бейджем (например: «Грюйер и Альпы»).',
									),
									array(
										'key'          => 'field_s_flexibol_route_day_timeline',
										'label'        => 'Таймлайн дня',
										'name'         => 's_flexibol_route_day_timeline',
										'type'         => 'repeater',
										'layout'       => 'row',
										'button_label' => 'Добавить пункт',
										'sub_fields'   => array(
											array(
												'key'   => 'field_s_flexibol_route_day_tl_time',
												'label' => 'Время / заголовок пункта',
												'name'  => 's_flexibol_route_time',
												'type'  => 'text',
											),
											array(
												'key'   => 'field_s_flexibol_route_day_tl_text',
												'label' => 'Текст',
												'name'  => 's_flexibol_route_text',
												'type'  => 'textarea',
												'rows'  => 4,
											),
										),
									),
									array(
										'key'          => 'field_s_flexibol_route_day_photos',
										'label'        => 'Фото дня',
										'name'         => 's_flexibol_route_day_photos',
										'type'         => 'repeater',
										'layout'       => 'row',
										'button_label' => 'Добавить фото',
										'sub_fields'   => array(
											array(
												'key'           => 'field_s_flexibol_route_day_photo',
												'label'         => 'Изображение',
												'name'          => 's_flexibol_route_photo',
												'type'          => 'image',
												'return_format' => 'array',
												'preview_size'  => 'medium',
												'library'       => 'all',
											),
										),
									),
								),
							),
						),
					),

					// Layout 9: Price table
					'layout_s_flexibol_price_table' => array(
						'key'     => 'layout_s_flexibol_price_table',
						'name'    => 's_flexibol_price_table',
						'label'   => 'Таблица цен',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_price_table_section_title',
								'label' => 'Заголовок блока',
								'name'  => 's_flexibol_price_table_section_title',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_price_table_background_image',
								'label'         => 'Фотка бекграунда',
								'name'          => 's_flexibol_price_table_background_image',
								'type'          => 'image',
								'instructions'  => 'Фон для секции table-price.',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_price_table_shadow_image',
								'label'         => 'Фотка тени',
								'name'          => 's_flexibol_price_table_shadow_image',
								'type'          => 'image',
								'instructions'  => 'Картинка вместо Ellipse371.webp (class elips371).',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							// Top section (fixed)
							array(
								'key'   => 'field_s_flexibol_price_table_top_input',
								'label' => 'Top: Input',
								'name'  => 's_flexibol_price_top_input',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_price_table_top_image',
								'label'         => 'Top: Image',
								'name'          => 's_flexibol_price_top_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							// Repeater: Price items
							array(
								'key'          => 'field_s_flexibol_price_table_items',
								'label'        => 'Price items',
								'name'         => 's_flexibol_price_items',
								'type'         => 'repeater',
								'layout'       => 'row',
								'button_label' => 'Add price item',
								'sub_fields'   => array(
									array(
										'key'           => 'field_s_flexibol_price_item_image_1',
										'label'         => 'Image 1',
										'name'          => 's_flexibol_price_image_1',
										'type'          => 'image',
										'return_format' => 'array',
										'preview_size'  => 'medium',
										'library'       => 'all',
									),
									array(
										'key'   => 'field_s_flexibol_price_item_title',
										'label' => 'Title',
										'name'  => 's_flexibol_price_title',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_item_input',
										'label' => 'Input',
										'name'  => 's_flexibol_price_input',
										'type'  => 'text',
									),
									array(
										'key'           => 'field_s_flexibol_price_item_image_2',
										'label'         => 'Image 2',
										'name'          => 's_flexibol_price_image_2',
										'type'          => 'image',
										'return_format' => 'array',
										'preview_size'  => 'medium',
										'library'       => 'all',
									),
									array(
										'key'   => 'field_s_flexibol_price_item_input_2',
										'label' => 'Input 2',
										'name'  => 's_flexibol_price_input_2',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_item_price',
										'label' => 'Price',
										'name'  => 's_flexibol_price_item_price',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_item_night',
										'label' => 'Night',
										'name'  => 's_flexibol_price_item_night',
										'type'  => 'text',
									),
								),
							),

							// Bottom blocks (3 fixed)
							array(
								'key'     => 'field_s_flexibol_price_bottom_block_1',
								'label'   => 'Bottom block 1',
								'name'    => 's_flexibol_price_bottom_block_1',
								'type'    => 'group',
								'layout'  => 'block',
								'sub_fields' => array(
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_1_top',
										'label' => 'Top input',
										'name'  => 's_flexibol_price_bb1_top',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_1_middle',
										'label' => 'Middle input',
										'name'  => 's_flexibol_price_bb1_middle',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_1_extra',
										'label' => 'Extra input',
										'name'  => 's_flexibol_price_bb1_extra',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_1_button_price',
										'label' => 'Button price (value)',
										'name'  => 's_flexibol_price_bb1_button_price',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_1_button_day',
										'label' => 'Day',
										'name'  => 's_flexibol_price_bb1_button_day',
										'type'  => 'text',
									),
								),
							),
							array(
								'key'     => 'field_s_flexibol_price_bottom_block_2',
								'label'   => 'Bottom block 2',
								'name'    => 's_flexibol_price_bottom_block_2',
								'type'    => 'group',
								'layout'  => 'block',
								'sub_fields' => array(
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_2_top',
										'label' => 'Top input',
										'name'  => 's_flexibol_price_bb2_top',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_2_middle',
										'label' => 'Middle input',
										'name'  => 's_flexibol_price_bb2_middle',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_2_extra',
										'label' => 'Extra input',
										'name'  => 's_flexibol_price_bb2_extra',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_2_button_price',
										'label' => 'Button price (value)',
										'name'  => 's_flexibol_price_bb2_button_price',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_2_button_day',
										'label' => 'Day',
										'name'  => 's_flexibol_price_bb2_button_day',
										'type'  => 'text',
									),
								),
							),
							array(
								'key'     => 'field_s_flexibol_price_bottom_block_3',
								'label'   => 'Bottom block 3',
								'name'    => 's_flexibol_price_bottom_block_3',
								'type'    => 'group',
								'layout'  => 'block',
								'sub_fields' => array(
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_3_top',
										'label' => 'Top input',
										'name'  => 's_flexibol_price_bb3_top',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_3_middle',
										'label' => 'Middle input',
										'name'  => 's_flexibol_price_bb3_middle',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_3_extra',
										'label' => 'Extra input',
										'name'  => 's_flexibol_price_bb3_extra',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_3_button_price',
										'label' => 'Button price (value)',
										'name'  => 's_flexibol_price_bb3_button_price',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_price_bottom_block_3_button_day',
										'label' => 'Day',
										'name'  => 's_flexibol_price_bb3_button_day',
										'type'  => 'text',
									),
								),
							),
						),
					),

					// Layout: Expert advice (советы эксперта)
					'layout_s_flexibol_advice' => array(
						'key'     => 'layout_s_flexibol_advice',
						'name'    => 's_flexibol_advice',
						'label'   => 'Советы эксперта',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_advice_section_title',
								'label' => 'Section title',
								'name'  => 's_flexibol_advice_section_title',
								'type'  => 'text',
							),
							array(
								'key'          => 'field_s_flexibol_advice_items',
								'label'        => 'Advice items',
								'name'         => 's_flexibol_advice_items',
								'type'         => 'repeater',
								'layout'       => 'row',
								'button_label' => 'Add advice',
								'sub_fields'   => array(
									array(
										'key'           => 'field_s_flexibol_advice_item_image',
										'label'         => 'Image',
										'name'          => 's_flexibol_advice_item_image',
										'type'          => 'image',
										'return_format' => 'array',
										'preview_size'  => 'medium',
										'library'       => 'all',
									),
									array(
										'key'   => 'field_s_flexibol_advice_item_title',
										'label' => 'Title (H3)',
										'name'  => 's_flexibol_advice_item_title',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_advice_item_text',
										'label' => 'Text',
										'name'  => 's_flexibol_advice_item_text',
										'type'  => 'textarea',
										'rows'  => 5,
									),
								),
							),
						),
					),

					// Layout: Opinion of the expert (only main photo in admin; layout images stay in theme)
					'layout_s_flexibol_expert' => array(
						'key'     => 'layout_s_flexibol_expert',
						'name'    => 's_flexibol_expert',
						'label'   => 'Мнение эксперта',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_expert_section_title',
								'label' => 'Заголовок блока',
								'name'  => 's_flexibol_expert_section_title',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_expert_background_image',
								'label'         => 'Фотка бекграунда',
								'name'          => 's_flexibol_expert_background_image',
								'type'          => 'image',
								'instructions'  => 'Фон для секции expert.',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_expert_shadow_image',
								'label'         => 'Фотка тени',
								'name'          => 's_flexibol_expert_shadow_image',
								'type'          => 'image',
								'instructions'  => 'Картинка вместо Ellipse372.webp (class ellipse372).',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_expert_photo',
								'label'         => 'Expert photo',
								'name'          => 's_flexibol_expert_photo',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
								'instructions'  => 'Main portrait only. Decorative images (quotes, icons, background) come from the theme layout.',
							),
							array(
								'key'   => 'field_s_flexibol_expert_name',
								'label' => 'Name',
								'name'  => 's_flexibol_expert_name',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_expert_role',
								'label' => 'Role',
								'name'  => 's_flexibol_expert_role',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_expert_stat_strong',
								'label' => 'Stat (bold part)',
								'name'  => 's_flexibol_expert_stat_strong',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_expert_stat_text',
								'label' => 'Stat (rest of line)',
								'name'  => 's_flexibol_expert_stat_text',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_expert_quote',
								'label' => 'Quote',
								'name'  => 's_flexibol_expert_quote',
								'type'  => 'textarea',
								'rows'  => 8,
							),
							array(
								'key'   => 'field_s_flexibol_expert_body',
								'label' => 'Body text',
								'name'  => 's_flexibol_expert_body',
								'type'  => 'textarea',
								'rows'  => 8,
							),
							array(
								'key'   => 'field_s_flexibol_expert_item_1_title',
								'label' => 'Item 1 — Title',
								'name'  => 's_flexibol_expert_item_1_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_expert_item_1_text',
								'label' => 'Item 1 — Text',
								'name'  => 's_flexibol_expert_item_1_text',
								'type'  => 'textarea',
								'rows'  => 5,
							),
							array(
								'key'   => 'field_s_flexibol_expert_item_2_title',
								'label' => 'Item 2 — Title',
								'name'  => 's_flexibol_expert_item_2_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_expert_item_2_text',
								'label' => 'Item 2 — Text',
								'name'  => 's_flexibol_expert_item_2_text',
								'type'  => 'textarea',
								'rows'  => 5,
							),
							array(
								'key'   => 'field_s_flexibol_expert_item_3_title',
								'label' => 'Item 3 — Title',
								'name'  => 's_flexibol_expert_item_3_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_expert_item_3_text',
								'label' => 'Item 3 — Text',
								'name'  => 's_flexibol_expert_item_3_text',
								'type'  => 'textarea',
								'rows'  => 5,
							),
						),
					),

					// Layout: Active leisure (активный отдых)
					'layout_s_flexibol_active_otd' => array(
						'key'     => 'layout_s_flexibol_active_otd',
						'name'    => 's_flexibol_active_otd',
						'label'   => 'Активный отдых',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_active_otd_section_title',
								'label' => 'Section title',
								'name'  => 's_flexibol_active_otd_section_title',
								'type'  => 'text',
							),
							array(
								'key'          => 'field_s_flexibol_active_otd_items',
								'label'        => 'Cards (up to 4)',
								'name'         => 's_flexibol_active_otd_items',
								'type'         => 'repeater',
								'layout'       => 'row',
								'min'          => 0,
								'max'          => 4,
								'button_label' => 'Add card',
								'sub_fields'   => array(
									array(
										'key'           => 'field_s_flexibol_active_otd_item_image',
										'label'         => 'Image',
										'name'          => 's_flexibol_active_otd_item_image',
										'type'          => 'image',
										'return_format' => 'array',
										'preview_size'  => 'medium',
										'library'       => 'all',
									),
									array(
										'key'   => 'field_s_flexibol_active_otd_item_title',
										'label' => 'Title',
										'name'  => 's_flexibol_active_otd_item_title',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_active_otd_item_text',
										'label' => 'Text',
										'name'  => 's_flexibol_active_otd_item_text',
										'type'  => 'textarea',
										'rows'  => 4,
									),
								),
							),
							array(
								'key'   => 'field_s_flexibol_active_otd_bottom_text',
								'label' => 'Bottom banner text',
								'name'  => 's_flexibol_active_otd_bottom_text',
								'type'  => 'textarea',
								'rows'  => 4,
							),
						),
					),

					// Layout: Where to stay (google-otel)
					'layout_s_flexibol_where_to_stay' => array(
						'key'     => 'layout_s_flexibol_where_to_stay',
						'name'    => 's_flexibol_where_to_stay',
						'label'   => 'Где остановиться',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_where_stay_section_title',
								'label' => 'Title',
								'name'  => 's_flexibol_where_stay_section_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_where_stay_lead_text',
								'label' => 'Text',
								'name'  => 's_flexibol_where_stay_lead_text',
								'type'  => 'textarea',
								'rows'  => 4,
								'instructions' => 'Shown under the section title (intro / subtitle).',
							),
							array(
								'key'          => 'field_s_flexibol_where_stay_cards',
								'label'        => 'Cards',
								'name'         => 's_flexibol_where_stay_cards',
								'type'         => 'repeater',
								'layout'       => 'row',
								'button_label' => 'Add card',
								'sub_fields'   => array(
									array(
										'key'   => 'field_s_flexibol_where_stay_card_title',
										'label' => 'Title',
										'name'  => 's_flexibol_where_stay_card_title',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_where_stay_card_text',
										'label' => 'Text',
										'name'  => 's_flexibol_where_stay_card_text',
										'type'  => 'textarea',
										'rows'  => 4,
									),
								),
							),
						),
					),

					// Layout: Parking
					'layout_s_flexibol_parking' => array(
						'key'     => 'layout_s_flexibol_parking',
						'name'    => 's_flexibol_parking',
						'label'   => 'Парковка',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_parking_section_title',
								'label' => 'Заголовок блока',
								'name'  => 's_flexibol_parking_section_title',
								'type'  => 'text',
							),
							array(
								'key'           => 'field_s_flexibol_parking_background_image',
								'label'         => 'Фотка бекграунда',
								'name'          => 's_flexibol_parking_background_image',
								'type'          => 'image',
								'instructions'  => 'Фон для секции parking.',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'           => 'field_s_flexibol_parking_shadow_image',
								'label'         => 'Фотка тени',
								'name'          => 's_flexibol_parking_shadow_image',
								'type'          => 'image',
								'instructions'  => 'Картинка вместо Ellipse374.webp (class ellipse374).',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
							),
							array(
								'key'   => 'field_s_flexibol_parking_subtitle',
								'label' => 'Subtitle',
								'name'  => 's_flexibol_parking_subtitle',
								'type'  => 'textarea',
								'rows'  => 4,
							),
							array(
								'key'          => 'field_s_flexibol_parking_cards',
								'label'        => 'Parking cards',
								'name'         => 's_flexibol_parking_cards',
								'type'         => 'repeater',
								'layout'       => 'row',
								'button_label' => 'Add card',
								'sub_fields'   => array(
									array(
										'key'   => 'field_s_flexibol_parking_card_title',
										'label' => 'Title',
										'name'  => 's_flexibol_parking_card_title',
										'type'  => 'text',
									),
									array(
										'key'   => 'field_s_flexibol_parking_card_text',
										'label' => 'Text',
										'name'  => 's_flexibol_parking_card_text',
										'type'  => 'textarea',
										'rows'  => 3,
									),
									array(
										'key'   => 'field_s_flexibol_parking_card_map_link',
										'label' => 'Map link',
										'name'  => 's_flexibol_parking_card_map_link',
										'type'  => 'url',
									),
									array(
										'key'           => 'field_s_flexibol_parking_card_button_label',
										'label'         => 'Button label',
										'name'          => 's_flexibol_parking_card_button_label',
										'type'          => 'text',
										'default_value' => 'На карте',
									),
								),
							),
							array(
								'key'   => 'field_s_flexibol_parking_footer_text',
								'label' => 'Footer note',
								'name'  => 's_flexibol_parking_footer_text',
								'type'  => 'textarea',
								'rows'  => 4,
								'instructions' => 'Text in the block below the cards (tips / holidays).',
							),
						),
					),

					// Layout: Footer expert (web-expert / Theresa Webb block)
					'layout_s_flexibol_footer_expert' => array(
						'key'     => 'layout_s_flexibol_footer_expert',
						'name'    => 's_flexibol_footer_expert',
						'label'   => 'Эксперт внизу страницы',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'           => 'field_s_flexibol_footer_expert_image',
								'label'         => 'Photo',
								'name'          => 's_flexibol_footer_expert_image',
								'type'          => 'image',
								'return_format' => 'array',
								'preview_size'  => 'medium',
								'library'       => 'all',
								'instructions'  => 'If empty, the theme default image is used.',
							),
							array(
								'key'   => 'field_s_flexibol_footer_expert_title',
								'label' => 'Heading',
								'name'  => 's_flexibol_footer_expert_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_s_flexibol_footer_expert_text',
								'label' => 'Text',
								'name'  => 's_flexibol_footer_expert_text',
								'type'  => 'textarea',
								'rows'  => 6,
							),
						),
					),

					// Layout 10: Editor block (single wysiwyg)
					'layout_s_flexibol_editor' => array(
						'key'     => 'layout_s_flexibol_editor',
						'name'    => 's_flexibol_editor',
						'label'   => 'Текстовый редактор',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_editor',
								'label' => 'Editor',
								'name'  => 's_flexibol_editor',
								'type'  => 'wysiwyg',
								'tabs'  => 'all',
							),
						),
					),

					// Layout 11: short_editor block (code/HTML textarea)
					'layout_s_flexibol_short_editor' => array(
						'key'     => 'layout_s_flexibol_short_editor',
						'name'    => 's_flexibol_short_editor',
						'label'   => 'Короткий редактор',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key'   => 'field_s_flexibol_short_editor',
								'label' => 'short_editor',
								'name'  => 's_flexibol_short_editor',
								'type'  => 'wysiwyg',
								'tabs'  => 'all',
							),
						),
					),

				),
			),
		),
		'location' => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
			),
		),
	) );
}


